#!/usr/bin/env python

import sys
import json
import sentry_sdk

# Read configuration parameters
alert_file = open(sys.argv[1])
hook_url = sys.argv[3]

sentry_sdk.init(hook_url)

# Read the alert file
alert_json = json.loads(alert_file.read())
alert_file.close()

# Extract issue fields
alert_level = alert_json['rule']['level']
description = alert_json['rule']['description']
agent_name = ""
if "agent" in alert_json:
    agent_name = alert_json['agent']['name']


with sentry_sdk.configure_scope() as scope:
    scope.set_extra("rule_data", alert_json['rule'])
# path = alert_json['syscheck']['path']

sentry_sdk.capture_message(description + " - " + agent_name + '- Alert level: ' + str(alert_level))

sys.exit(0)
